channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=24.0
- pip:
  - mlflow==2.15.0
  - cloudpickle==2.2.1
  - enum34==1.1.10
  - numpy==1.24.2
  - pathlib==1.0.1
  - psutil==5.9.5
  - scikit-learn==1.3.0
  - scipy==1.11.2
name: mlflow-env
